export enum Caching {
  ALL_USER = 'all_user',
  ALL_EVENT = 'all_event',
  ALL_NFT = 'all_nft',
  ALL_NFT_BOUGHT = 'all_nft_bought',
  ALL_SUPPORT = 'all_support',
  SUPPORT_BY_TICKET = 'support_by_ticket',
  SEARCH_USER = 'search_user',
  USER_BY_ID = 'user_by_id',
  USER_BY_USERNAME = 'user_by_username',
  USER_BY_IDS = 'user_by_ids',
  USER_BY_WALLET_ADDRESS = 'user_by_wallet_address',
  USER_BY_EMAIL = 'user_by_email',
  USER_BY_TIME = 'user_by_time',
  EVENT_BY_ID = 'event_by_id',
  EVENT_BY_IDS = 'event_by_ids',
  EVENT_TICKET_BY_ID = 'event_ticket_by_id',
  EVENT_TICKET_BY_IDS = 'event_ticket_by_ids',
  NFT_BY_ID = 'nft_by_id',
  NFT_BOUGHT_BY_USER_ID = 'nft_bought_by_user_id',
  NFT_BOUGHT_BY_NFT_IDS = 'nft_bought_by_nft_ids',
  NFT_BOUGHT_BY_USER_AND_NFT = 'nft_bought_by_user_and_nft',
  CHANNELS_BY_USER = 'channels_by_user',
  CHANNEL_BY_NAMES = 'channel_by_names',
  AIRDROP_STATUS = 'airdrop_status'
}
